### ISSUE TITLE
I keep getting this error....

### ISSUE THREAD

**Issue by jodavis16** [Azanor/Baubles#125]
---- Minecraft Crash Report ----
// Quite honestly, I wouldn't worry myself about that.

Time: 3/27/16 2:20 AM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at md.zazpro.mod.common.baubles.Ring_Core.clientTick(Ring_Core.java:102)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_18_Ring_Core_clientTick_ClientTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at cpw.mods.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:325)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1587)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Full crash report: 
[crash-2016-03-27_02.20.38-client.txt](https://github.com/Azanor/Baubles/files/191142/crash-2016-03-27_02.20.38-client.txt)

Any ideas why??

**Comment by gigabit101** [comment]
this is not a baubles issue looks like zazpro's issue

**Comment by Azanor** [comment]
yup
