### ISSUE TITLE
1.9-1.2.0.2 in Forge 1.9 build 1907 blocks the player onhurt event with mobs

### ISSUE THREAD

**Issue by kreezxil** [Azanor/Baubles#133]
This is when connected to a dedicated server.
```
[12:58:23] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_91]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_91]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [g.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:664) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:386) [la.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:609) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:467) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.NullPointerException
        at md.zazpro.mod.common.baubles.Pendant_Core.onHurt(Pendant_Core.java:130) ~[Pendant_Core.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_34_Pendant_Core_onHurt_LivingHurtEvent.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49) ~[ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140) ~[EventBus.class:?]
        at net.minecraftforge.common.ForgeHooks.onLivingHurt(ForgeHooks.java:480) ~[ForgeHooks.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70665_d(EntityLivingBase.java:1256) ~[sa.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:872) ~[sa.class:?]
        at net.minecraft.entity.passive.EntityAnimal.func_70097_a(SourceFile:64) ~[vw.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_71059_n(EntityPlayer.java:1271) ~[zj.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.func_71059_n(EntityPlayerMP.java:1222) ~[lr.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147340_a(NetHandlerPlayServer.java:1042) ~[mb.class:?]
        at net.minecraft.network.play.client.CPacketUseEntity.func_148833_a(SourceFile:68) ~[ir.class:?]
        at net.minecraft.network.play.client.CPacketUseEntity.func_148833_a(SourceFile:12) ~[ir.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fh$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_91]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_91]
        at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[g.class:?]
        ... 5 more

```

**Comment by GirafiStudios** [comment]
This is not caused by Baubles, it's caused by whatever mod "md.zazpro.mod" is.

**Comment by kreezxil** [comment]
I just realized that, thank you.
