### ISSUE TITLE
[BETA 6] .NoClassDefFoundError: scala/actors/threadpool/Arrays error

### ISSUE THREAD

**Issue by PrinceOfAmber** [Azanor/Baubles#145]
Runtime error: happens after joining a world. full log:

---- Minecraft Crash Report ----
// I just don't know what went wrong :(

Time: 06/10/16 5:39 AM
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: scala/actors/threadpool/Arrays
	at baubles.api.cap.BaublesContainer.setChanged(BaublesContainer.java:62)
	at baubles.common.event.EventHandlerEntity.playerJoin(EventHandlerEntity.java:44)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_10_EventHandlerEntity_playerJoin_EntityJoinWorldEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:168)
	at net.minecraft.world.World.func_72838_d(World.java:1129)
	at net.minecraft.world.WorldServer.func_72838_d(WorldServer.java:1063)
	at net.minecraft.server.management.PlayerList.func_72377_c(PlayerList.java:368)
	at net.minecraft.server.management.PlayerList.initializeConnectionToPlayer(PlayerList.java:163)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:260)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:73)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:287)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:732)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: scala.actors.threadpool.Arrays
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 19 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 413359528 bytes (394 MB) / 921477120 bytes (878 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.32 Powered by Forge 12.18.1.2093 13 mods loaded, 13 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.1.2093.jar) 
	UCHIJAAAA	Forge{12.18.1.2093} [Minecraft Forge] (forge-1.10.2-12.18.1.2093.jar) 
	UCHIJAAAA	Baubles{1.3.BETA6} [Baubles] (Baubles-1.10.2-1.3.BETA6.jar) 
	UCHIJAAAA	JEI{3.10.0.263} [Just Enough Items] (jei_1.10.2-3.10.0.263.jar) 
	UCHIJAAAA	cyclicmagic{1.7.12} [Cyclic] (Cyclic-1.10.2-1.DEV.jar) 
	UCHIJAAAA	ftbl{2.1.0} [FTBLib] (FTBLib-1.9.4-2.1.0-pre3.jar) 
	UCHIJAAAA	ftbu{2.1.0} [FTBUtilities] (FTBUtilities-1.9.4-2.1.0-pre3.jar) 
	UCHIJAAAA	harvestchevsky{b8} [Gentle Harvest] (Gentle_Harvest_1.9_b8.jar) 
	UCHIJAAAA	ironchest{1.10.2-7.0.11.797} [Iron Chest] (ironchest-1.10.2-7.0.11.797.jar) 
	UCHIJAAAA	mantle{1.10.2-1.0.0.jenkins170} [Mantle] (Mantle-1.10.2-1.0.0.jar) 
	UCHIJAAAA	tconstruct{1.10.2-2.5.2.jenkins352} [Tinkers' Construct] (TConstruct-1.10.2-2.5.2.jar) 
	UCHIJAAAA	tp{1.0.0} [Tiny Progressions] (tinyprogressions-1.10.2-1.0.6-release.jar) 
	Loaded coremods (and transformers): 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)

	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['LazarussLong'/375, l='BLARG', x=116.89, y=64.00, z=22.64]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by Azanor** [comment]
Stupid eclipse importing the wrong version of Arrays. Will fix and reupload Beta6

**Comment by PrinceOfAmber** [comment]
Thanks!
