### ISSUE TITLE
Baubles Crashing on Generation of a New World

### ISSUE THREAD

**Issue by AlphaBeta116** [Azanor/Baubles#211]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-1.7.6-1.11.2.jar)
  AstralCore (astralsorcery-1.4.3.jar)
  FarseekCoreMod (Farseek-1.11-2.1.jar)
  IvToolkit (IvToolkit-1.3.3.jar)
Contact their authors BEFORE contacting forge

// Oops.

Time: 6/21/17 9:25 PM
Description: Exception in server tick loop

java.lang.NoSuchMethodError: baubles.api.BaublesApi.getBaublesHandler(Lnet/minecraft/entity/player/EntityPlayer;)Lbaubles/api/cap/IBaublesItemHandler;
	at baubles.common.event.EventHandlerEntity.playerJoin(EventHandlerEntity.java:62)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_15_EventHandlerEntity_playerJoin_EntityJoinWorldEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraft.world.World.func_72838_d(World.java:1198)
	at net.minecraft.world.WorldServer.func_72838_d(WorldServer.java:1066)
	at net.minecraft.server.management.PlayerList.func_72377_c(PlayerList.java:355)
	at net.minecraft.server.management.PlayerList.initializeConnectionToPlayer(PlayerList.java:161)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:262)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:73)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:211)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:287)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:743)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 348603224 bytes (332 MB) / 950923264 bytes (906 MB) up to 4281597952 bytes (4083 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.38 Powered by Forge 13.20.0.2228 24 mods loaded, 24 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.0.2228.jar) 
	UCHIJAAAA	forge{13.20.0.2228} [Minecraft Forge] (forge-1.11.2-13.20.0.2228.jar) 
	UCHIJAAAA	ivtoolkit{1.3.3} [IvToolkit] (minecraft.jar) 
	UCHIJAAAA	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.11.jar) 
	UCHIJAAAA	astralsorcery{1.4.3} [Astral Sorcery] (astralsorcery-1.4.3.jar) 
	UCHIJAAAA	battletowers{1.5.8} [Battle Towers] (BattleTowers-1.11.2.jar) 
	UCHIJAAAA	baubles{1.4.3} [Baubles] (Baubles-1.11-1.4.3.jar) 
	UCHIJAAAA	openterraingenerator{v5} [Open Terrain Generator] (OpenTerrainGenerator-1.11.2-v5.jar) 
	UCHIJAAAA	biomebundle{5.1} [Biome Bundle] (Biome_Bundle-1.11.2-v5.1.jar) 
	UCHIJAAAA	botania{r1.9-344} [Botania] (Botania r1.9-344.jar) 
	UCHIJAAAA	dailies{1.11.2-6} [Bailey's Dailies] (dailies-1.11.2-6.jar) 
	UCHIJAAAA	farseek{2.1} [Farseek] (Farseek-1.11-2.1.jar) 
	UCHIJAAAA	llibrary{1.7.6} [LLibrary] (llibrary-1.7.6-1.11.2.jar) 
	UCHIJAAAA	iceandfire{1.1.1} [Ice and Fire] (iceandfire-1.1.1.jar) 
	UCHIJAAAA	jei{4.5.0.289} [Just Enough Items] (jei_1.11.2-4.5.0.289.jar) 
	UCHIJAAAA	minecolonies{1.11.2-0.8.2786} [MineColonies] (minecolonies-universal-1.11.2-0.8.2786.jar) 
	UCHIJAAAA	mowziesmobs{1.3.3} [Mowzie's Mobs] (mowziesmobs-1.3.3.jar) 
	UCHIJAAAA	reccomplex{1.3.2} [Recurrent Complex] (RecurrentComplex-1.4.jar) 
	UCHIJAAAA	roguelike{1.6.6} [Roguelike Dungeons] (RoguelikeDungeons-1.11.2-1.6.6.jar) 
	UCHIJAAAA	roots{0.020} [Roots 2] (roots-2-0.020.jar) 
	UCHIJAAAA	ruins{16.5} [Ruins Mod] (Ruins-1.11.2.jar) 
	UCHIJAAAA	streams{0.3} [Streams] (Streams-1.11-0.3.jar) 
	Loaded coremods (and transformers): 
llibrary (llibrary-1.7.6-1.11.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
AstralCore (astralsorcery-1.4.3.jar)
  
FarseekCoreMod (Farseek-1.11-2.1.jar)
  farseek.core.FarseekClassTransformer
IvToolkit (IvToolkit-1.3.3.jar)
  
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['GildedCrafter'/829, l='New World', x=-162.50, y=74.00, z=227.50]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by Azanor** [comment]
Is this still a problem?

From the looks of it one of the mods you are using isn't isn't compatible with the latest baubles.
