### ISSUE TITLE
deploader 1.7.10 crash newest baubles installed

### ISSUE THREAD

**Issue by lithric** [Azanor/Baubles#238]
I've looked at all of the complaints mentioning this crash but they seem to be different from the problem I'm having. When I downloaded thaumcraft with baubles downloaded and saw this crash, I knew that I should probably check if anybody else has had this problem. I looked at all the comments and tried resolving my issue the same way they resolved theirs. I downloaded the most recent version of baubles in 1.7.10 which is 1.0.1.10 and also got the most recent version of thaumcraft in 1.7.10 which is 4.2.3.5. In the comments, it said that you could skip the deploader part by downloading the mod manually so I did that. I clicked launch and then, it brought up the deploader screen and crashed because I couldn't get it to load. Also when I was reading the comments, I saw that you could possibly use the dropbox link but that didn't work either. I also saw in the comments that something could be wrong with the way I set up the files so I looked and saw nothing that changes when it crashes. I tried going to somewhere else to download the mod but it still didn't work. I think I spent about 2 hours trying to get my minecraft to stop crashing on launch because of deploader. Anyway, do you, all that is holy and praised for the greatest achievements in human history, never weary or tired when faced with devastation, the most powerful and kind being on the face of every atom in the infinite universe *takes breath*, have an answer to my problem. Please, I'm begging ya.

**Comment by Azanor** [comment]
Could you post the crash report please?

**Comment by lithric** [comment]
I couldn't get the exact crash report that Minecraft gives you, but I did find a good alternative. I tried to get the file and even looked through the files and ran the game about 15 or so times to get the crash report file to appear in the crash reports folder but every time I refreshed to get it to pop up, it wouldn't pop up. So I did the next best thing and got the Minecraft game launcher output. I don't want to cause you too much trouble so here. I feel like I'm being interrogated, just to let you know.


Preparing to launch minecraft client for 1.7.10-Forge10.13.4.1614-1.7.10
--
21:59:33 | launcher | Couldn't get hash for com/typesafe/config/1.2.1/config-1.2.1.jar from http://files.minecraftforge.net/maven/com/typesafe/config/1.2.1/config-1.2.1.jar.sha1: HTTP 404: Not Found
21:59:33 | launcher | Couldn't get hash for net/minecraftforge/forge/1.7.10-10.13.4.1614-1.7.10/forge-1.7.10-10.13.4.1614-1.7.10.jar from http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.7.10-10.13.4.1614-1.7.10/forge-1.7.10-10.13.4.1614-1.7.10.jar.sha1: HTTP 404: Not Found
21:59:33 | launcher | Have local file C:/Users\Noname\AppData\Roaming\.minecraft\libraries\net/minecraftforge/forge/1.7.10-10.13.4.1614-1.7.10/forge-1.7.10-10.13.4.1614-1.7.10.jar but don't know what size or hash it should be. Have to assume it's good.
21:59:33 | launcher | Couldn't get hash for org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar from http://files.minecraftforge.net/maven/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar.sha1: HTTP 404: Not Found
21:59:33 | launcher | Couldn't get hash for org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar from http://files.minecraftforge.net/maven/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar.sha1: HTTP 404: Not Found
21:59:33 | launcher | Couldn't get hash for org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar from http://files.minecraftforge.net/maven/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar.sha1: HTTP 404: Not Found
21:59:33 | launcher | Couldn't get hash for com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar from http://files.minecraftforge.net/maven/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar.sha1: HTTP 404: Not Found
21:59:33 | launcher | Have local file C:/Users\Perfect\AppData\Roaming\.minecraft\libraries\com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar but don't know what size or hash it should be. Have to assume it's good.
21:59:33 | launcher | Have local file C:/Users\NotGivingName\AppData\Roaming\.minecraft\libraries\com/typesafe/config/1.2.1/config-1.2.1.jar but don't know what size or hash it should be. Have to assume it's good.
21:59:33 | launcher | Have local file C:/Users\Why\AppData\Roaming\.minecraft\libraries\org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar but don't know what size or hash it should be. Have to assume it's good.
21:59:33 | launcher | Have local file C:/Users\SoMany\AppData\Roaming\.minecraft\libraries\org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar but don't know what size or hash it should be. Have to assume it's good.
21:59:33 | launcher | Have local file C:/Users\NameThings\AppData\Roaming\.minecraft\libraries\org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar but don't know what size or hash it should be. Have to assume it's good.
21:59:33 | launcher | Couldn't get hash for org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar from http://files.minecraftforge.net/maven/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar.sha1: HTTP 404: Not Found
21:59:33 | launcher | Couldn't get hash for org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar from http://files.minecraftforge.net/maven/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar.sha1: HTTP 404: Not Found
21:59:33 | launcher | Have local file C:/Users\Haya\AppData\Roaming\.minecraft\libraries\org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar but don't know what size or hash it should be. Have to assume it's good.
21:59:33 | launcher | Have local file C:/Users\Billy\AppData\Roaming\.minecraft\libraries\org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar but don't know what size or hash it should be. Have to assume it's good.
21:59:33 | launcher | Couldn't get hash for org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar from http://files.minecraftforge.net/maven/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar.sha1: HTTP 404: Not Found
21:59:33 | launcher | Have local file C:/Users\NameIsCringe\AppData\Roaming\.minecraft\libraries\org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar but don't know what size or hash it should be. Have to assume it's good.
21:59:33 | launcher | Couldn't get hash for org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar from http://files.minecraftforge.net/maven/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar.sha1: HTTP 404: Not Found
21:59:33 | launcher | Have local file C:/Users\Nope\AppData\Roaming\.minecraft\libraries\org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar but don't know what size or hash it should be. Have to assume it's good.
21:59:33 | launcher | Couldn't get hash for org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar from http://files.minecraftforge.net/maven/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar.sha1: HTTP 404: Not Found
21:59:33 | launcher | Couldn't get hash for org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar from http://files.minecraftforge.net/maven/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar.sha1: HTTP 404: Not Found
21:59:33 | launcher | Have local file C:/Users\CornFlakes\AppData\Roaming\.minecraft\libraries\org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar but don't know what size or hash it should be. Have to assume it's good.
21:59:33 | launcher | Have local file C:/Users\WayATon\AppData\Roaming\.minecraft\libraries\org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar but don't know what size or hash it should be. Have to assume it's good.
21:59:33 | launcher | Couldn't get hash for 1.7.10 jar from https://s3.amazonaws.com/Minecraft.Download/versions/1.7.10/1.7.10.jar.sha1: HTTP 403: Forbidden
21:59:33 | launcher | Have local file C:/Users\NoSlips\AppData\Roaming\.minecraft\versions\1.7.10/1.7.10.jar but don't know what size or hash it should be. Have to assume it's good.
21:59:33 | launcher | Checking installations.
21:59:33 | launcher | Minecraft client 1.7.10-Forge10.13.4.1614-1.7.10 is ready to start.
21:59:33 | launcher | Starting!
21:59:33 | launcher | Using default game log configuration client-1.7.xml (outputs XML)
21:59:34 | LaunchWrapper | Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
21:59:34 | LaunchWrapper | Using primary tweak class name cpw.mods.fml.common.launcher.FMLTweaker
21:59:34 | LaunchWrapper | Calling tweak class cpw.mods.fml.common.launcher.FMLTweaker
21:59:34 | FML | Forge Mod Loader version 7.99.40.1614 for Minecraft 1.7.10 loading
21:59:34 | FML | Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_25, running on Windows 10:amd64:10.0, installed at C:\Program Files (x86)\Minecraft\runtime\jre-x64\1.8.0_25
21:59:34 | FML | The coremod codechicken.core.launch.CodeChickenCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
16:59:40 | game | Downloading file https://dl.dropboxusercontent.com/u/47135879//Baubles-1.7.10-1.0.1.10.jar   <log4j:Event logger="STDERR" timestamp="1516330780867" level="INFO" thread="main">     <log4j:Message><![CDATA[[java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.RuntimeException: A download error occured]]></log4j:Message>   </log4j:Event>
16:59:40 | monitor | expected <
21:59:40 | STDERR | [java.lang.Throwable$WrappedPrintStream:println:748]: 	at codechicken.core.launch.DepLoader$DepLoadInst.download(DepLoader.java:354)
21:59:40 | STDERR | [java.lang.Throwable$WrappedPrintStream:println:748]: 	at codechicken.core.launch.DepLoader$DepLoadInst.load(DepLoader.java:480)
21:59:40 | STDERR | [java.lang.Throwable$WrappedPrintStream:println:748]: 	at codechicken.core.launch.DepLoader$DepLoadInst.loadDeps(DepLoader.java:466)
21:59:40 | STDERR | [java.lang.Throwable$WrappedPrintStream:println:748]: 	at codechicken.core.launch.DepLoader$DepLoadInst.load(DepLoader.java:449)
21:59:40 | STDERR | [java.lang.Throwable$WrappedPrintStream:println:748]: 	at codechicken.core.launch.DepLoader.load(DepLoader.java:584)
21:59:40 | STDERR | [java.lang.Throwable$WrappedPrintStream:println:748]: 	at codechicken.core.launch.CodeChickenCorePlugin.<init>(CodeChickenCorePlugin.java:47)
21:59:40 | STDERR | [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
21:59:40 | STDERR | [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
21:59:40 | STDERR | [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
21:59:40 | STDERR | [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
21:59:40 | STDERR | [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.Class.newInstance(Class.java:438)
21:59:40 | STDERR | [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:501)
21:59:40 | STDERR | [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:389)
21:59:40 | STDERR | [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:221)
21:59:40 | STDERR | [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90)
21:59:40 | STDERR | [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67)
21:59:40 | STDERR | [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34)
21:59:40 | STDERR | [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:126)
21:59:40 | STDERR | [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
21:59:40 | STDERR | [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
21:59:40 | STDERR | [java.lang.Throwable$WrappedPrintStream:println:748]: Caused by: java.io.FileNotFoundException: https://dl.dropboxusercontent.com/u/47135879//Baubles-1.7.10-1.0.1.10.jar
21:59:40 | STDERR | [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
21:59:40 | STDERR | [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
21:59:40 | STDERR | [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
21:59:40 | STDERR | [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
21:59:40 | STDERR | [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1888)
21:59:40 | STDERR | [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1883)
21:59:40 | STDERR | [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.security.AccessController.doPrivileged(Native Method)
21:59:40 | STDERR | [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1882)
21:59:40 | STDERR | [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1455)
21:59:40 | STDERR | [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:90)
21:59:40 | STDERR | [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1431)
21:59:40 | STDERR | [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1429)
21:59:40 | STDERR | [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.security.AccessController.doPrivileged(Native Method)
21:59:40 | STDERR | [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.security.AccessController.doPrivileged(AccessController.java:713)
21:59:40 | STDERR | [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1428)
21:59:40 | STDERR | [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
21:59:40 | STDERR | [java.lang.Throwable$WrappedPrintStream:println:748]: 	at codechicken.core.launch.DepLoader$DepLoadInst.download(DepLoader.java:341)
21:59:40 | STDERR | [java.lang.Throwable$WrappedPrintStream:println:748]: 	... 19 more
21:59:40 | STDERR | [java.lang.Throwable$WrappedPrintStream:println:748]: Caused by: java.io.FileNotFoundException: https://dl.dropboxusercontent.com/u/47135879//Baubles-1.7.10-1.0.1.10.jar
21:59:40 | STDERR | [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1834)
21:59:40 | STDERR | [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:90)
21:59:40 | STDERR | [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1431)
21:59:40 | STDERR | [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1429)
21:59:40 | STDERR | [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.security.AccessController.doPrivileged(Native Method)
21:59:40 | STDERR | [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.security.AccessController.doPrivileged(AccessController.java:713)
21:59:40 | STDERR | [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1428)
21:59:40 | STDERR | [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.www.protocol.http.HttpURLConnection.getHeaderField(HttpURLConnection.java:2929)
21:59:40 | STDERR | [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.net.URLConnection.getHeaderFieldLong(URLConnection.java:629)
21:59:40 | STDERR | [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.net.URLConnection.getContentLengthLong(URLConnection.java:501)
21:59:40 | STDERR | [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.net.URLConnection.getContentLength(URLConnection.java:485)
21:59:40 | STDERR | [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getContentLength(HttpsURLConnectionImpl.java:398)
21:59:40 | STDERR | [java.lang.Throwable$WrappedPrintStream:println:748]: 	at codechicken.core.launch.DepLoader$DepLoadInst.download(DepLoader.java:340)
21:59:40 | STDERR | [java.lang.Throwable$WrappedPrintStream:println:748]: 	... 19 more
21:59:40 | FML | An error occurred trying to configure the minecraft home at C:\Users\YouThoughtIWouldSlip?...Ha\AppData\Roaming\.minecraft for Forge Mod Loader java.lang.RuntimeException: A download error occured 	at codechicken.core.launch.DepLoader$DepLoadInst.download(DepLoader.java:354) 	at codechicken.core.launch.DepLoader$DepLoadInst.load(DepLoader.java:480) 	at codechicken.core.launch.DepLoader$DepLoadInst.loadDeps(DepLoader.java:466) 	at codechicken.core.launch.DepLoader$DepLoadInst.load(DepLoader.java:449) 	at codechicken.core.launch.DepLoader.load(DepLoader.java:584) 	at codechicken.core.launch.CodeChickenCorePlugin.<init>(CodeChickenCorePlugin.java:47) 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) 	at java.lang.reflect.Constructor.newInstance(Constructor.java:408) 	at java.lang.Class.newInstance(Class.java:438) 	at cpw.mods.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:501) 	at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:389) 	at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:221) 	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90) 	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67) 	at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34) 	at cpw.mods.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:126) 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) Caused by: java.io.FileNotFoundException: https://dl.dropboxusercontent.com/u/47135879//Baubles-1.7.10-1.0.1.10.jar 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) 	at java.lang.reflect.Constructor.newInstance(Constructor.java:408) 	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1888) 	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1883) 	at java.security.AccessController.doPrivileged(Native Method) 	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1882) 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1455) 	at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:90) 	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1431) 	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1429) 	at java.security.AccessController.doPrivileged(Native Method) 	at java.security.AccessController.doPrivileged(AccessController.java:713) 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1428) 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254) 	at codechicken.core.launch.DepLoader$DepLoadInst.download(DepLoader.java:341) 	... 19 more Caused by: java.io.FileNotFoundException: https://dl.dropboxusercontent.com/u/47135879//Baubles-1.7.10-1.0.1.10.jar 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1834) 	at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:90) 	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1431) 	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1429) 	at java.security.AccessController.doPrivileged(Native Method) 	at java.security.AccessController.doPrivileged(AccessController.java:713) 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1428) 	at sun.net.www.protocol.http.HttpURLConnection.getHeaderField(HttpURLConnection.java:2929) 	at java.net.URLConnection.getHeaderFieldLong(URLConnection.java:629) 	at java.net.URLConnection.getContentLengthLong(URLConnection.java:501) 	at java.net.URLConnection.getContentLength(URLConnection.java:485) 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getContentLength(HttpsURLConnectionImpl.java:398) 	at codechicken.core.launch.DepLoader$DepLoadInst.download(DepLoader.java:340) 	... 19 more
21:59:40 | LaunchWrapper | Unable to launch java.lang.RuntimeException: A download error occured 	at codechicken.core.launch.DepLoader$DepLoadInst.download(DepLoader.java:354) 	at codechicken.core.launch.DepLoader$DepLoadInst.load(DepLoader.java:480) 	at codechicken.core.launch.DepLoader$DepLoadInst.loadDeps(DepLoader.java:466) 	at codechicken.core.launch.DepLoader$DepLoadInst.load(DepLoader.java:449) 	at codechicken.core.launch.DepLoader.load(DepLoader.java:584) 	at codechicken.core.launch.CodeChickenCorePlugin.<init>(CodeChickenCorePlugin.java:47) 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) 	at java.lang.reflect.Constructor.newInstance(Constructor.java:408) 	at java.lang.Class.newInstance(Class.java:438) 	at cpw.mods.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:501) 	at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:389) 	at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:221) 	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90) 	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67) 	at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34) 	at cpw.mods.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:126) 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) Caused by: java.io.FileNotFoundException: https://dl.dropboxusercontent.com/u/47135879//Baubles-1.7.10-1.0.1.10.jar 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) 	at java.lang.reflect.Constructor.newInstance(Constructor.java:408) 	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1888) 	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1883) 	at java.security.AccessController.doPrivileged(Native Method) 	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1882) 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1455) 	at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:90) 	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1431) 	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1429) 	at java.security.AccessController.doPrivileged(Native Method) 	at java.security.AccessController.doPrivileged(AccessController.java:713) 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1428) 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254) 	at codechicken.core.launch.DepLoader$DepLoadInst.download(DepLoader.java:341) 	... 19 more Caused by: java.io.FileNotFoundException: https://dl.dropboxusercontent.com/u/47135879//Baubles-1.7.10-1.0.1.10.jar 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1834) 	at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:90) 	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1431) 	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1429) 	at java.security.AccessController.doPrivileged(Native Method) 	at java.security.AccessController.doPrivileged(AccessController.java:713) 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1428) 	at sun.net.www.protocol.http.HttpURLConnection.getHeaderField(HttpURLConnection.java:2929) 	at java.net.URLConnection.getHeaderFieldLong(URLConnection.java:629) 	at java.net.URLConnection.getContentLengthLong(URLConnection.java:501) 	at java.net.URLConnection.getContentLength(URLConnection.java:485) 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getContentLength(HttpsURLConnectionImpl.java:398) 	at codechicken.core.launch.DepLoader$DepLoadInst.download(DepLoader.java:340) 	... 19 more
16:59:40 | game | Exception in thread "main"   <log4j:Event logger="STDERR" timestamp="1516330780884" level="INFO" thread="main">     <log4j:Message><![CDATA[[java.lang.Throwable$WrappedPrintStream:println:748]: cpw.mods.fml.relauncher.FMLSecurityManager$ExitTrappedException]]></log4j:Message>   </log4j:Event>
16:59:40 | monitor | expected <
21:59:40 | STDERR | [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:25)
21:59:40 | STDERR | [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
21:59:40 | STDERR | [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.Runtime.exit(Runtime.java:107)
21:59:40 | STDERR | [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.System.exit(System.java:968)
21:59:40 | STDERR | [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
21:59:40 | STDERR | [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

I think this code is funny. Just assume it's good. Error:12(sh.63:/grid=false) Render=NotGonnaSayExactly
I'm sorry for wasting your time if it's my fault. I'll try to figure out the problem myself next time a crash like this happens.

 Just a note:
 I looked at the code a little bit and saw that my username was there and thaumcraft... I don't know exactly. Anyway, I changed my username in the code, a bit.

**Comment by lithric** [comment]
It's updated

**Comment by lithric** [comment]
If you want all of the code, and just to warn, there are 2,394 sentences of code. Not lines, Sentences. Just let me know. Those were just the errors. 
list:
Debug:2291
infos:70
warnings:27
errors:6
