### ISSUE TITLE
[1.12.2] NoSuchMethodError crash

### ISSUE THREAD

**Issue by xorinzor** [Azanor/Baubles#241]
We're not quite sure what action triggered this, but it caused our server to crash.

```
Description: Exception in server tick loop

java.lang.NoSuchMethodError: baubles.common.network.PacketSync.<init>(Lnet/minecraft/entity/player/EntityPlayer;I)V
        at vazkii.botania.common.core.handler.InternalMethodHandler.sendBaubleUpdatePacket(InternalMethodHandler.java:263)
        at vazkii.botania.common.item.equipment.bauble.ItemMagnetRing.onTossItem(ItemMagnetRing.java:66)
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_743_ItemMagnetRing_onTossItem_ItemTossEvent.invoke(.dynamic)
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
        at net.minecraftforge.common.ForgeHooks.onPlayerTossEvent(ForgeHooks.java:681)
        at net.minecraft.entity.player.EntityPlayer.func_71019_a(EntityPlayer.java:711)
        at net.minecraft.inventory.Container.func_75134_a(Container.java:489)
        at net.minecraft.inventory.ContainerPlayer.func_75134_a(ContainerPlayer.java:93)
        at net.minecraft.entity.player.EntityPlayer.func_70106_y(EntityPlayer.java:1507)
        at net.minecraft.world.World.func_72900_e(World.java:1242)
        at net.minecraft.server.management.PlayerList.func_72367_e(PlayerList.java:412)
        at net.minecraft.network.NetHandlerPlayServer.func_147231_a(NetHandlerPlayServer.java:849)
        at net.minecraft.network.NetworkManager.func_179293_l(NetworkManager.java:457)
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:213)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:788)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
        at java.lang.Thread.run(Thread.java:748)
```

Full crashlog: https://pastebin.com/vLvVeh20

All the Mods 3 modpack (version 5.7)
Baubles 1.5.2
Botania r1.10-352

**Comment by KasperFranz** [comment]
Really an issue at https://github.com/Vazkii/Botania/issues/2509

**Comment by williewillus** [comment]
this is already fixed in botania
