### ISSUE TITLE
[1.12.2] Dropping items with Magnet Ring equipped does not drop items

### ISSUE THREAD

**Issue by JonoColwell** [Azanor/Baubles#243]
Attempting to drop items with the magnet ring equipped causes the following error

> [18:43:27] [Server thread/FATAL]: Error executing task
> --
> java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: baubles.common.network.PacketSync.<init>(Lnet/minecraft/entity/player/EntityPlayer;I)V
> at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_131]
> at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_131]
> at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
> at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721) [MinecraftServer.class:?]
> at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
> at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
> at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
> at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
> Caused by: java.lang.NoSuchMethodError: baubles.common.network.PacketSync.<init>(Lnet/minecraft/entity/player/EntityPlayer;I)V
> at vazkii.botania.common.core.handler.InternalMethodHandler.sendBaubleUpdatePacket(InternalMethodHandler.java:263) ~[InternalMethodHandler.class:?]
> at vazkii.botania.common.item.equipment.bauble.ItemMagnetRing.onTossItem(ItemMagnetRing.java:66) ~[ItemMagnetRing.class:?]
> at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_755_ItemMagnetRing_onTossItem_ItemTossEvent.invoke(.dynamic) ~[?:?]
> at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
> at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179) ~[EventBus.class:?]
> at net.minecraftforge.common.ForgeHooks.onPlayerTossEvent(ForgeHooks.java:681) ~[ForgeHooks.class:?]
> at net.minecraft.entity.player.EntityPlayer.func_71040_bB(EntityPlayer.java:703) ~[aed.class:?]
> at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:651) ~[pa.class:?]
> at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:40) ~[lp.class:?]
> at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:10) ~[lp.class:?]
> at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
> at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_131]
> at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_131]
> at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
> ... 5 more
> 

And the items are not dropped on the ground, this after getting the crash reported in #241 worked fine prior

**Comment by vincania** [comment]
I experienced the same problem...downgraded baubles after and it worked fine.

**Comment by Tntdruid** [comment]
items i drop just get deleted from the game.

**Comment by Aphyxia** [comment]
Also, crashed while trying to drop items:
```
java.lang.NoSuchMethodError: baubles.common.network.PacketSync.<init>(Lnet/minecraft/entity/player/EntityPlayer;I)V
	at vazkii.botania.common.core.handler.InternalMethodHandler.sendBaubleUpdatePacket(InternalMethodHandler.java:263)
	at vazkii.botania.common.item.equipment.bauble.ItemMagnetRing.onTossItem(ItemMagnetRing.java:66)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_699_ItemMagnetRing_onTossItem_ItemTossEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.common.ForgeHooks.onPlayerTossEvent(ForgeHooks.java:681)
	at net.minecraft.entity.player.EntityPlayer.func_71019_a(EntityPlayer.java:711)
	at net.minecraft.inventory.Container.func_75134_a(Container.java:489)
	at net.minecraft.inventory.ContainerPlayer.func_75134_a(ContainerPlayer.java:93)
	at net.minecraft.entity.player.EntityPlayer.func_70106_y(EntityPlayer.java:1507)
	at net.minecraft.world.World.func_72900_e(World.java:1242)
	at net.minecraft.server.management.PlayerList.func_72367_e(PlayerList.java:412)
	at net.minecraft.network.NetHandlerPlayServer.func_147231_a(NetHandlerPlayServer.java:849)
	at net.minecraft.network.NetworkManager.func_179293_l(NetworkManager.java:457)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:213)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:788)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by Pullle** [comment]
Wearing Manasteel Armor from Botania AND wearing a Mana Ring from it on a Baubles slot isn't a problem. But if you get damage, like from an arrow or a creeper blowing up, the server will stop.
[crash-2018-01-23_16.00.37-server.txt](https://github.com/Azanor/Baubles/files/1658168/crash-2018-01-23_16.00.37-server.txt)
[crash-2018-01-23_20.13.09-server.txt](https://github.com/Azanor/Baubles/files/1658169/crash-2018-01-23_20.13.09-server.txt)
