### ISSUE TITLE
[Crash] Crash on startup while using baubles 1.5.2

### ISSUE THREAD

**Issue by Markillo45** [Azanor/Baubles#269]
Having Startup crashes when using Baubles 1.5.2 either with other mods or by itself.
Any help would be greatly appreciated.
https://pastebin.com/Pi8hPWbS

**Comment by Roschl** [comment]
Looks like a curse problem ... maybe try it without using the curse launcher, setting up minecraft forge in the original minecraft path?!

**Comment by Vasinqs** [comment]
@Rurpot  Im having the same issue. 

---- Minecraft Crash Report ----

WARNING: coremods are present:
  CreativePatchingLoader (CreativeCore_v1.9.35_mc1.12.2.jar)
  ItemPatchingLoader (ItemPhysic_Full_1.4.17_mc1.12.2.jar)
  FMLModule (mdxlib-3.0.0.6.jar)
  OTGCorePlugin (OTG-Core.jar)
  SSLoadingPlugin (SereneSeasons-1.12.2-1.2.13-universal.jar)
Contact their authors BEFORE contacting forge

// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 12/9/18 12:48 PM
Description: Initializing game

java.lang.NoSuchMethodError: net.minecraft.block.properties.PropertyBool.create(Ljava/lang/String;)Lnet/minecraft/block/properties/PropertyBool;
	at com.tmtravlr.jaff.blocks.BlockTank.<clinit>(BlockTank.java:33)
	at com.tmtravlr.jaff.JAFFMod.<clinit>(JAFFMod.java:91)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:526)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:593)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.tmtravlr.jaff.blocks.BlockTank.<clinit>(BlockTank.java:33)
	at com.tmtravlr.jaff.JAFFMod.<clinit>(JAFFMod.java:91)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:526)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:593)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 287834144 bytes (274 MB) / 771751936 bytes (736 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2784 31 mods loaded, 31 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                   | Version       | Source                                    | Signature                                |
	|:----- |:-------------------- |:------------- |:----------------------------------------- |:---------------------------------------- |
	| LC    | minecraft            | 1.12.2        | minecraft.jar                             | None                                     |
	| LC    | mcp                  | 9.42          | minecraft.jar                             | None                                     |
	| LC    | FML                  | 8.0.99.99     | forge-1.12.2-14.23.5.2784.jar             | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LC    | forge                | 14.23.5.2784  | forge-1.12.2-14.23.5.2784.jar             | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LC    | creativecoredummy    | 1.0.0         | minecraft.jar                             | None                                     |
	| LC    | itemphysic           | 1.4.0         | minecraft.jar                             | None                                     |
	| LC    | otgcore              | 1.12.2 - v7   | minecraft.jar                             | None                                     |
	| LC    | uncraftingtable      | 1.8-beta6     | [1.12]UncraftingTable-1.8-beta6.jar       | None                                     |
	| LC    | mdxlib               | 3.0.0.6       | mdxlib-3.0.0.6.jar                        | None                                     |
	| LC    | avp                  | 6.0.0.15      | aliensvspredator-6.0.0.15.jar             | None                                     |
	| LC    | baubles              | 1.5.2         | Baubles-1.12-1.5.2.jar                    | None                                     |
	| LC    | openterraingenerator | v6            | OpenTerrainGenerator-1.12.2+-+v6.jar      | e9f7847a78c5342af5b0a9e04e5abc0b554d69e0 |
	| LC    | biomebundle          | 5.1           | Biome_Bundle-1.12.2-v6.1.jar              | None                                     |
	| LC    | extendedrenderer     | v1.0          | CoroUtil-1.12.2.jar                       | None                                     |
	| LC    | coroutil             | 1.12.1-1.2.14 | CoroUtil-1.12.2.jar                       | None                                     |
	| LC    | configmod            | v1.0          | CoroUtil-1.12.2.jar                       | None                                     |
	| LC    | creativecore         | 1.9.9         | CreativeCore_v1.9.35_mc1.12.2.jar         | None                                     |
	| LC    | customspawner        | 3.11.4        | CustomMobSpawner-3.11.4.jar               | None                                     |
	| LC    | torohealthmod        | 1.12.2-11     | Damage-Indicators-1.12.2.jar              | None                                     |
	| LC    | mocreatures          | 12.0.5        | DrZharks MoCreatures Mod-12.0.5.jar       | None                                     |
	| LC    | dynamictrees         | 1.12.2-0.9.1d | DynamicTrees-1.12.2-0.9.1d.jar            | None                                     |
	| LC    | harvestcraft         | 1.12.2z       | Pam's+HarvestCraft+1.12.2za.jar           | None                                     |
	| LC    | dynamictreesphc      | 1.12.2-0.1.1a | DynamicTreesPHC-1.12.2-0.1.1a.jar         | None                                     |
	| LC    | exoticbirds          | 1.0           | Exotic-Birds-1.12.2.jar                   | None                                     |
	| LC    | journeymap           | 1.12.2-5.5.2  | JourneyMap-Mod-1.12.2-Unlimited.jar       | None                                     |
	| L     | jaff                 | 1.7_for_1.12  | JustAFewFish-1.7_for_1.12-deobf.jar       | None                                     |
	| L     | lucky                | 7.5.0         | Lucky-Block-Mod-1.12.zip                  | None                                     |
	| L     | radixcore            | 1.12.x-2.2.1  | RadixCore-1.12.x-2.2.1-universal.jar      | None                                     |
	| L     | sereneseasons        | 1.2.13        | SereneSeasons-1.12.2-1.2.13-universal.jar | None                                     |
	| L     | thaumcraft           | 6.1.BETA26    | Thaumcraft-1.12.2-6.1.BETA26.jar          | None                                     |
	| L     | weather2             | 1.12.1-2.6.12 | Weather-Storms-Tornadoes-Mod-1.12.2.jar   | None                                     |

	Loaded coremods (and transformers): 
CreativePatchingLoader (CreativeCore_v1.9.35_mc1.12.2.jar)
  
ItemPatchingLoader (ItemPhysic_Full_1.4.17_mc1.12.2.jar)
  com.creativemd.itemphysic.ItemTransformer
FMLModule (mdxlib-3.0.0.6.jar)
  com.arisux.mdx.AccessTransformer
OTGCorePlugin (OTG-Core.jar)
  com.pg85.otg.forge.asm.OTGClassTransformer
SSLoadingPlugin (SereneSeasons-1.12.2-1.2.13-universal.jar)
  sereneseasons.asm.transformer.EntityRendererTransformer
  sereneseasons.asm.transformer.WorldTransformer
	GL info: ' Vendor: 'Intel' Version: '4.5.0 - Build 24.20.100.6292' Renderer: 'Intel(R) UHD Graphics 620'
	Launched Version: 1.12.2-forge1.12.2-14.23.5.2784
	LWJGL: 2.9.4
	OpenGL: Intel(R) UHD Graphics 620 GL version 4.5.0 - Build 24.20.100.6292, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i3-8130U CPU @ 2.20GHz
