### ISSUE TITLE
[1.7.10] [Server thread/ERROR] [Baubles]: Could not save baubles file for player

### ISSUE THREAD

**Issue by ProsperCraft** [Azanor/Baubles#47]
Using forge-1.7.10-10.13.0.1183

[09:04:05] [Server thread/INFO]: dehtrim_mwb has just earned the achievement [Taking Inventory]
[09:04:21] [Server thread/INFO]: dehtrim_mwb lost connection: TextComponent{text='Disconnected', siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null}}
java.io.FileNotFoundException: ./apocalypse/players/dehtrim_mwb.baub (No such file or directory)
[09:04:21] [Server thread/INFO]: dehtrim_mwb left the game
        at java.io.FileOutputStream.open(Native Method)
[09:04:21] [Server thread/ERROR] [Baubles]: Could not save baubles file for player dehtrim_mwb
        at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:171)
        at baubles.common.lib.PlayerHandler.savePlayerBaubles(PlayerHandler.java:143)
        at baubles.common.network.EventHandlerNetwork.playerUpdateEvent(EventHandlerNetwork.java:26)
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_86_EventHandlerNetwork_playerUpdateEvent_PlayerEvent.invoke(.dynamic)
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:51)
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:122)
        at cpw.mods.fml.common.FMLCommonHandler.firePlayerLoggedOut(FMLCommonHandler.java:554)
        at net.minecraft.server.management.ServerConfigurationManager.func_72367_e(ServerConfigurationManager.java:305)
        at net.minecraft.network.NetHandlerPlayServer.func_147231_a(NetHandlerPlayServer.java:628)
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:158)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:335)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by ProsperCraft** [comment]
The report was made 1 year ago when 1.7.2 was the thing ;)
